name: Reusable workflow for syncing from template source
on:
  workflow_call:
    inputs:
      template-repo:
        description: 'Source repo in owner/repo format'
        required: true
        type: string
      create-pr:
        description: 'Should a PR be created for changes'
        default: true
        required: false
        type: boolean
      update-branch-name:
        description: 'branch name to use for update commits'
        default: 'source-template-updates'
        required: false
        type: string
    secrets:
      workflowPAT:
        description: 'A PAT scoped to be able to update workflows'
        required: false
      templatePAT:
        description: 'A PAT scoped to be able to read the template repo'
        required: false

jobs:
  check-for-updates:
    name: Check if updates
    runs-on: ubuntu-latest
    if: ${{ inputs.template-repo != github.repository }}
    steps:
      # get first commit time of main repo
      - name: main repo creation time
        id: main-repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          created=$(curl -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/$REPO | jq -r .created_at)
          echo "::set-output name=created::$created"
          
      # get last commit time of template source repo
      - name: template repo update time
        id: template-repo
        env:
          TOKEN: ${{ secrets.templatePAT }}
          REPO: ${{ inputs.template-repo }}
        run: |
          updated=$(curl -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/$REPO | jq -r .pushed_at)
          echo "::set-output name=updated::$updated"

      # compare datetimes
      - name: compare datetimes
        id: compare
        env:
          CREATED: ${{ steps.main-repo.outputs.created }}
          UPDATED: ${{ steps.template-repo.outputs.updated }}
        run: |
          if [[ "$UPDATED" > "$CREATED" ]]; then
            echo "Template repo update time is newer than main repo creation time."
            echo "Updates to template repo assumed."
            status="true"
          else
            status="false"
          fi
          echo "::set-output name=updates::$status"

    outputs:
      updates: ${{ steps.compare.outputs.updates }}

  sync:
    name: Pull from template source
    runs-on: ubuntu-latest
    if: ${{ inputs.template-repo != github.repository && needs.check-for-updates.outputs.updates == 'true' }}
    needs: check-for-updates
    steps:
      # checkout full repo
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.workflowPAT }}
          fetch-depth: 0
          path: main

      # checkout template repo
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.template-repo }}
          token: ${{ secrets.templatePAT }}
          fetch-depth: 0
          path: template

      # config user name and email
      - name: Config repo user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
        working-directory: ./main

      # add local template repo as remote
      - name: Add local template repo as remote
        run: git remote add template ../template/.git
        working-directory: ./main

       # if creating PR for changes, create branch
      - name: Create branch for updates
        if: ${{ inputs.create-pr }}
        run: git checkout ${{ inputs.update-branch-name }} || git checkout -b ${{ inputs.update-branch-name }}
        working-directory: ./main

      # fetch template commits
      - name: Fetch commits
        run: git fetch --all
        working-directory: ./main

      # try merging changes from template repo
      - name: Try merge
        id: merge
        run: |
          current_sha=$(git rev-parse HEAD)
          git merge template/main --allow-unrelated-histories -X theirs
          if [[ $current_sha == $(git rev-parse HEAD) ]]; then
            echo "No merge"
            echo "::set-output name=merge::false"
          else
            echo "Merge!!"
            echo "::set-output name=merge::true"
          fi
        working-directory: ./main

      # if merge, push changes
      - name: Push changes
        if: ${{ steps.merge.outputs.merge != 'false' }}
        run: git push origin --all
        working-directory: ./main

      # if merge, create PR
      - name: Create PR
        if: ${{ inputs.create-pr && steps.merge.outputs.merge != 'false' }}
        run: gh pr create --title "Upstream update" --body "Updates from source template." --base main --head ${{ inputs.update-branch-name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./main
